### PR TITLE
Integrated and extended @peternijssen version (#10)

### PR DESCRIPTION
**Pull request by eavanvalkenburg**
I integrated the work @peternijssen did for #10 I added a extra method get_relevant_deliveries and property methods in the classes, created new Readme with a new test script. And finally did Black formatting on the whole thing.

I also unified the method names, so get_... always as a plural so get_deliveries, get_letters, etc.

### CODE REVIEW

**Comment by peternijssen** [comment]
Awesome! You were capable of running the test local? I had issues with that, but they seem to be related to my environment. Just hadn't had the time yet to recheck.

If you could rename the version to 1.2.0, then my MR can be closed and we can use this one.

Would be great if we could tag this version afterwards, then I'll update the component in HA.

**Comment by eavanvalkenburg** [comment]
Just made some further refinements and change the version to 1.2.0

**Review by iMicknl — APPROVED** [review]
Nice work @peternijssen & @eavanvalkenburg! :-)
@eavanvalkenburg is this one ready to merge?

**Comment by eavanvalkenburg** [comment]
LGTM

**Comment by peternijssen** [comment]
@iMicknl any chance of merging and tagging it soon? No pressure, but would love to update the HA component in the upcoming version. Thanks!

**Comment by iMicknl** [comment]
@peternijssen I will merge and publish on monday. Thanks for the reminder.

**Comment by iMicknl** [comment]
@peternijssen newest version has been published on PyPi. https://pypi.org/project/postnl-api/

**Pull request merged**
