### PR TITLE
Fix Unauthorized_Exception by adding a User-Agent

### PR DESCRIPTION
**Pull request by IcyPalm**
Added a User-Agent to requests since PostNL seems to filter based on those now.

### CODE REVIEW

**Comment by IcyPalm** [comment]
Also added a fix for an error I noticed during testing:  A package enroute with no known date yet.
`Package expected but not in sorting process yet`

**Comment by IcyPalm** [comment]
@iMicknl if it looks good to you, could you tag this version so the Home Assistant package can be updated and fixed?

cc @peternijssen

**Review by iMicknl — APPROVED** [review]
@IcyPalm thanks for your contribution! Good spot, apparently the User Agent has been removed in #11. Previous used User Agent was `'user-agent': 'PostNL/1 CFNetwork/889.3 Darwin/17.2.0'`.

**Comment by iMicknl** [comment]
@IcyPalm, could you maybe bump the version number and add it to the changelog? Then I will merge + publish. 

Otherwise I will do it later this week and release it. :-)

**Comment by peternijssen** [comment]
Since 1.0.2 is still being used in HA, it seems like the old header value is no longer valid. We might need to update the user agent periodically.

**Comment by IcyPalm** [comment]
Done! 

`Committed and Pushed on Train WiFi on my way back from the Home Assistant State of the Union ;)`

**Comment by iMicknl** [comment]
Thanks @IcyPalm! Unfortunately I couldn't attend yesterday.. 
https://pypi.org/project/postnl-api/1.2.2/

**Comment by IcyPalm** [comment]
Thanks for merging and publishing! A shame you missed it 😢  
Maybe next year! 😃

**Pull request merged**
